"""Add reset password fields to User

Revision ID: 164034f9f625
Revises: 270c36addda2
Create Date: 2026-04-14 18:06:04.699205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164034f9f625'
down_revision = '270c36addda2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_password_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_password_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_password_expires')
        batch_op.drop_column('reset_password_token')

    # ### end Alembic commands ###
